server {
    listen 80;
    server_name localhost;

    # Directorio donde se copian los archivos compilados de React
    root /usr/share/nginx/html;
    index index.html;

    # Si el archivo NO existe, intenta servir index.html (esto arregla el 404)
    location / {
        try_files $uri $uri/ /index.html;
    }
}