spring.application.name=ToolRent

# Why: We change the default port (8080) to 8090 to avoid collisions if you are running
# the frontend or another service on the standard port on the same machine.
server.port=8090

# ENDPOINT CONNECTION: Points to the physical location of the data.
# The application will attempt to open a socket here to read/write persistent records.
spring.datasource.url=jdbc:postgresql://localhost:5432/tool_rent_db
spring.datasource.username=postgres
spring.datasource.password=12345

# Why: Allows the application to automatically modify the database structure (add tables/columns)
# to match your Java code every time it starts. Useful for dev, dangerous for production.
spring.jpa.hibernate.ddl-auto=update

# Custom property used to identify which logical group of users we are working with.
app.keycloak.target-realm=toolrent-realm 

# ENDPOINT VALIDATION: The "Source of Truth". The backend uses this URL to download public keys
# and verify that the tokens sent by the frontend were actually signed by this trusted server.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/toolrent-realm

# Why: Security is invisible by default. We enable verbose logging here to see exactly
# *why* a request gets rejected (e.g., "Expired Token" vs "Invalid Signature") during development.
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

# ENDPOINT ADMIN API: These credentials allow the backend to act as a "Super Admin" programmatically.
# Why: Necessary if your app needs to create new users or manage roles directly from the Java code
# without a human logging into the Keycloak console.
keycloak.auth-server-url=http://localhost:9090
keycloak.realm=master
keycloak.resource=admin-cli
keycloak.username=maria
keycloak.password=123123

# Why: Acts as the public identifier for this application when talking to the Auth Server.
spring.security.oauth2.resourceserver.jwt.client-id=toolrent-realm

# Why: The application's private password. It serves as a handshake credential to prove
# to Keycloak that this backend service is authorized to validate tokens or exchange data.
spring.security.oauth2.resourceserver.jwt.client-secret=SkHT3JSmbzCBmoCYyL0D6cdu5rZL1SrW

# Why: "X-Ray vision" for the database. It prints the actual SQL queries being executed,
# allowing you to spot performance issues or logic errors in how Hibernate talks to Postgres.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate=DEBUG