spring.application.name=ToolRent
server.port=8090
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/tool_rent_db
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=create

