events {}

http {
    upstream backend_servers {
        # Aquí apuntamos a las 3 réplicas en el puerto 8090 (que definiste antes)
        server toolrent-backend-1:8090;
        server toolrent-backend-2:8090;
        server toolrent-backend-3:8090;
    }

    server {
        listen 80;

        # Todo lo que empiece por /api se manda a los backends
        location /api {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Todo lo demás se manda al Frontend
        location / {
            proxy_pass http://toolrent-frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}